version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.20.7
    working_directory: ~/ra-data-feathers
    steps:
      - checkout
      - restore_cache:
          key: mdph-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: mdph-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/root/.cache/yarn"
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
